server:
  port: 9100
  servlet:
    context-path: /shopping
spring:
  datasource:
    # Reemplaza [YOUR-PASSWORD] con la contraseña que pusiste al crear el proyecto en Supabase
    url: jdbc:postgresql://db.xjcehcevipfbwaikwtcm.supabase.co:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    # Muestra los queries SQL en la consola (útil para debuggear)
    show-sql: true
    hibernate:
      # 'update' crea las tablas automáticamente si no existen
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Esto ayuda a que Postgres entienda mejor los tipos de datos de Java
        jdbc:
          lob:
            non_contextual_creation: true
app:
  cors:
    allowed-origins: http://localhost:9200
